version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: node --inspect=0.0.0.0:9229 server.js --host 0.0.0.0 --port 3000 --cache /usr/src/app/cache
    environment:
      - NODE_ENV=development